# Settings for the Adesto Tech AT25DF641-SSHD-T 8MiB SPI flash
# for the Oak Dev Tech Icy Tree M0 (SAMD21) feather board.
# Source: https://www.digikey.com/product-detail/en/adesto-technologies/AT25SF641-SDHD-T/1265-1180-1-ND/
# Datasheet: https://www.adestotech.com/wp-content/uploads/doc8693.pdf
total_size = 0x800000 # 8 MiB
memory_type = 0x48
capacity = 0x00
has_sector_protection = true
start_up_time_us = 10000
max_clock_speed_mhz = 85
quad_enable_bit_mask = 0x00
write_status_register_split = false
6b_quad_read = false
32_qspi_write = false
