# Settings for the Adesto Tech AT25DF081A 1MiB SPI flash. It's on the SAMD21
# Xplained board.
# Datasheet: https://www.adestotech.com/wp-content/uploads/doc8715.pdf
total_size = 0x100000 # 1 MiB
memory_type = 0x45
capacity = 0x01
has_sector_protection = true
start_up_time_us = 10000
max_clock_speed_mhz = 85
quad_enable_bit_mask = 0x00
write_status_register_split = false
6b_quad_read = false
32_qspi_write = false
