# Settings for the Gigadevice GD25Q32C 4MiB SPI flash.
# Datasheet: http://www.elm-tech.com/en/products/spi-flash-memory/gd25q32/gd25q32.pdf
total_size = 0x400000 # 4 MiB
capacity = 0x16
write_status_register_split = true
e7_quad_word_read = true
01_continuous_status_write = false
