# Settings for the Winbond W25Q80DV 1MiB SPI flash.. Note that W25Q80DL has a different memory type (0x60)
# Datasheet: https://www.winbond.com/resource-files/w25q80dv%20dl_revh_10022015.pdf
total_size = 0x100000 # 1 MiB
start_up_time_us = 5000
memory_type = 0x40
capacity = 0x14
max_clock_speed_mhz = 104
quad_enable_bit_mask = 0x02
quad_enable_status_byte = 2
write_status_register_split = false
6b_quad_read = true
32_qspi_write = false
