# Settings for the Winbond W25Q64JV-IM 8MiB SPI flash. Note that JV-IQ has a different .memory_type (0x40)
# Datasheet: http://www.winbond.com/resource-files/w25q64jv%20revj%2003272018%20plus.pdf
total_size = 0x800000 # 8 MiB
start_up_time_us = 5000
memory_type = 0x70
capacity = 0x17
max_clock_speed_mhz = 133
quad_enable_bit_mask = 0x02
quad_enable_status_byte = 2
write_status_register_split = true
01_continuous_status_write = true
6b_quad_read = true
32_qspi_write = true
