# Settings for the Winbond W25Q16JV-IM 2MiB SPI flash. Note that JV-IQ has a different .memory_type (0x40)
# Datasheet: https://www.winbond.com/resource-files/w25q16jv%20spi%20revf%2005092017.pdf
total_size = 0x200000 # 2 MiB
start_up_time_us = 5000
memory_type = 0x70
capacity = 0x15
max_clock_speed_mhz = 133
quad_enable_bit_mask = 0x02
write_status_register_split = false
6b_quad_read = true
32_qspi_write = true
