# Settings for the Winbond W25Q32BV 4MiB SPI flash.
# Datasheet: https://www.winbond.com/resource-files/w25q32bv_revi_100413_wo_automotive.pdf
total_size = 0x400000 # 4 MiB
start_up_time_us = 10000
memory_type = 0x60
capacity = 0x16
max_clock_speed_mhz = 104
quad_enable_bit_mask = 0x02
quad_enable_status_byte = 2
write_status_register_split = false
01_continuous_status_write = true
6b_quad_read = true
32_qspi_write = false
