# Settings for the Winbond W25Q128JV-SQ 16MiB SPI flash. Note that JV-IM has a different .memory_type (0x70)
# Datasheet: https://www.winbond.com/resource-files/w25q128jv%20revf%2003272018%20plus.pdf
total_size = 0x1000000 # 16 MiB
start_up_time_us = 5000
memory_type = 0x40
capacity = 0x18
max_clock_speed_mhz = 133
quad_enable_bit_mask = 0x02
quad_enable_status_byte = 2
write_status_register_split = false
6b_quad_read = true
32_qspi_write = true
