start_up_time_us = 10000
manufacturer_id = 0x20
memory_type = 0xBA
max_clock_speed_mhz = 108
quad_enable_bit_mask = 0x02
has_sector_protection = false
write_status_register_split = false
quad_enable_status_byte = 1
6b_quad_read = true
32_qspi_write = true
