# Settings for the Micron N25Q256A 256Mb (32MiB) QSPI flash.
# Datasheet: https://www.micron.com/-/media/client/global/documents/products/data-sheet/nor-flash/serial-nor/n25q/n25q_256mb_3v.pdf
total_size = 0x1000000 # 16 MiB
capacity = 0x19
