# Settings for the Cypress (was Spansion) S25FL216K 2MiB SPI flash.
# Datasheet: http://www.cypress.com/file/197346/download
total_size = 0x200000 # 2 MiB
start_up_time_us = 10000
memory_type = 0x40
capacity = 0x15
max_clock_speed_mhz = 65
6b_quad_read = false
32_qspi_write = false
