# Settings for the Macronix MX25L51245G 64MiB SPI flash.
# Datasheet: https://www.macronix.com/Lists/Datasheet/Attachments/7437/MX25L51245G,%203V,%20512Mb,%20v1.6.pdf
total_size = 0x4000000 # 64 MiB
start_up_time_us = 5000
manufacturer_id = 0xc2
memory_type = 0x20
capacity = 0x1a
max_clock_speed_mhz = 133
quad_enable_bit_mask = 0x40
has_sector_protection = false
