# Settings for the Macronix MX25L1606 2MiB SPI flash.
# Datasheet:
total_size = 0x200000 # 2 MiB
start_up_time_us = 5000
manufacturer_id = 0xc2
memory_type = 0x20
capacity = 0x15
max_clock_speed_mhz = 8
quad_enable_bit_mask = 0x40
has_sector_protection = false
