# Settings for the Macronix MX25L12833F 16MiB SPI flash
# Datasheet: https://www.macronix.com/Lists/Datasheet/Attachments/7447/MX25L12833F,%203V,%20128Mb,%20v1.0.pdf
total_size = 0x1000000 # 16 MiB
start_up_time_us = 5000
manufacturer_id = 0xc2
memory_type = 0x20
capacity = 0x18
max_clock_speed_mhz = 133
quad_enable_bit_mask = 0x40
has_sector_protection = true
