# Settings for the Macronix MX25R6435F 8MiB SPI flash.
# Datasheet: http://www.macronix.com/Lists/Datasheet/Attachments/7428/MX25R6435F,%20Wide%20Range,%2064Mb,%20v1.4.pdf
# By default its in lower power mode which can only do 8mhz. In high power mode it can do 80mhz.
total_size = 0x800000 # 8 MiB
start_up_time_us = 5000
manufacturer_id = 0xc2
memory_type = 0x28
capacity = 0x17
max_clock_speed_mhz = 8
quad_enable_bit_mask = 0x40
has_sector_protection = false
