# Settings for the Macronix MX25L3233F 4MiB SPI flash.
# Datasheet: http://www.macronix.com/Lists/Datasheet/Attachments/7426/MX25L3233F,%203V,%2032Mb,%20v1.6.pdf
total_size = 0x400000 # 4 MiB
start_up_time_us = 5000
manufacturer_id = 0xc2
memory_type = 0x20
capacity = 0x16
max_clock_speed_mhz = 133
quad_enable_bit_mask = 0x40
has_sector_protection = false
