name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10-2020-q4'
      - run: arm-none-eabi-gcc --version
      - name: Build Boot2 files
        run: |
          which arm-none-eabi-gcc || true
          arm-none-eabi-gcc --version
          python3 build.py /home/runner/gcc-arm-none-eabi-10.2020.4-linux/gcc-arm-none-eabi-10-2020-q4-major --verbose
        shell: bash
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Boot2_Files
          path: generated
