start_up_time_us = 10000
manufacturer_id = 0x9d
memory_type = 0x60
max_clock_speed_mhz = 133
quad_enable_bit_mask = 0x02
has_sector_protection = true
write_status_register_split = false
quad_enable_status_byte = 2
6b_quad_read = true
32_qspi_write = true
